# Generated by Django 2.2.7 on 2019-12-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=18, help_text='Latitude coordinate for squirrel sighting point', max_digits=22)),
                ('y', models.DecimalField(decimal_places=18, help_text='Longitude coordinate for squirrel sighting point', max_digits=22)),
                ('unique_squirrel_id', models.CharField(help_text='Identification tag for each squirrel sightings', max_length=30)),
                ('shift', models.CharField(help_text='sighting morning or afternoon', max_length=5)),
                ('date', models.CharField(help_text='sighting day and month', max_length=5)),
                ('age', models.CharField(help_text='adult or juvenile', max_length=10)),
                ('primary_fur_color', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=20)),
                ('specific_location', models.CharField(max_length=100)),
                ('running', models.BooleanField()),
                ('chasing', models.BooleanField()),
                ('climbing', models.BooleanField()),
                ('eating', models.BooleanField()),
                ('foraging', models.BooleanField()),
                ('other_activities', models.CharField(max_length=50)),
                ('kuks', models.BooleanField()),
                ('quaas', models.BooleanField()),
                ('moans', models.BooleanField()),
                ('tail_flags', models.BooleanField()),
                ('tail_twitches', models.BooleanField()),
                ('approaches', models.BooleanField()),
                ('indifferent', models.BooleanField()),
                ('runs_from', models.BooleanField()),
            ],
        ),
    ]
