# Generated by Django 2.2.7 on 2019-12-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X', models.DecimalField(decimal_places=18, help_text='Longitude coordinate for squirrel sighting point', max_digits=22)),
                ('Y', models.DecimalField(decimal_places=18, help_text='Longitude coordinate for squirrel sighting point', max_digits=22)),
                ('Unique_Squirrel_ID', models.CharField(help_text='Identification tag for each squirrel sightings', max_length=30)),
            ],
        ),
    ]
