# Generated by Django 2.2.7 on 2019-12-07 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findsquirrels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='date',
            field=models.CharField(help_text='sighting day and month', max_length=10),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='location',
            field=models.CharField(help_text='Ground Plane or Above Ground', max_length=20),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='primary_fur_color',
            field=models.CharField(help_text='Gray,Cinnamon or Black', max_length=20),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='specific_location',
            field=models.CharField(help_text='your commentary', max_length=100),
        ),
    ]
