# Generated by Django 2.2.7 on 2019-12-07 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findsquirrels', '0002_auto_20191207_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squirrel',
            name='id',
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='unique_squirrel_id',
            field=models.CharField(help_text='Identification tag for each squirrel sightings', max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='x',
            field=models.DecimalField(decimal_places=18, help_text='Longitude coordinate for squirrel sighting point', max_digits=22),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='y',
            field=models.DecimalField(decimal_places=18, help_text='Latitude coordinate for squirrel sighting point', max_digits=22),
        ),
    ]
